version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:  
      - .env
    restart: always
    working_dir: /app
